import { 
  Post1, 
  Post2,
  Post3,
  Post4,
  Post5,
  Post6 } from "../assets"

export const cars = [
  
    {
     key: 1,
     image: Post1,
     title: "Lebron",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 2,
     image: Post1,
     title: " James",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 3,
     image: Post1,
     title: "Lebron",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 4,
     image: Post1,
     title: "James",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 5,
     image: Post1,
     title: "Lebron",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 6,
     image: Post1,
     title: "James",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 7,
     image: Post1,
     title: "Lebron",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   {
     key: 8,
     image: Post1,
     title: "James",
     amount: "2.00$",
     more: "nkjhjk",
     area: "NK",
     text: "THE GOAT",
   },
   ];
export   const electronic = [
    {
      key: 1,
      image: Post6,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 2,
      image: Post6,
      title: " James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 3,
      image: Post6,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 4,
      image: Post6,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 5,
      image: Post6,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 6,
      image: Post6,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 7,
      image: Post6,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 8,
      image: Post6,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
  ];
  
  export  const furniture = [
    {
      key: 1,
      image: Post3,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 2,
      image: Post3,
      title: " James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 3,
      image: Post3,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 4,
      image: Post3,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 5,
      image: Post3,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 6,
      image: Post3,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 7,
      image: Post3,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 8,
      image: Post3,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
  ];
  export  const mobile = [
    {
      key: 1,
      image: Post5,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 2,
      image: Post5,
      title: " James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 3,
      image: Post5,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 4,
      image: Post5,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 5,
      image: Post5,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 6,
      image: Post5,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 7,
      image: Post5,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 8,
      image: Post5,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
  ];
  export  const property = [
    {
      key: 1,
      image: Post2,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 2,
      image: Post2,
      title: " James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 3,
      image: Post2,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 4,
      image: Post2,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 5,
      image: Post2,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 6,
      image: Post2,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 7,
      image: Post2,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 8,
      image: Post2,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
  ];
  export  const services = [
    {
      key: 1,
      image: Post4,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 2,
      image: Post4,
      title: " James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 3,
      image: Post4,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 4,
      image: Post4,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 5,
      image: Post4,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 6,
      image: Post4,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 7,
      image: Post4,
      title: "Lebron",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
    {
      key: 8,
      image: Post4,
      title: "James",
      amount: "2.00$",
      more: "nkjhjk",
      area: "NK",
      text: "THE GOAT",
    },
  ];